<?php

use Illuminate\Database\Seeder;

class SeedItemsDescriptionRows extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (DB::table('itemsDescription')->count('itemsGroupId') > 0) {
            return ;
        }

        DB::table('itemsDescription')->insert([
            ['itemsGroupId' => 3,'specTitle' => 'BL-Hxx37A 0402 Series','specDescription' => 'BL-Hxx37A 0402 Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 4,'specTitle' => 'BL-Hxx36G 0603 0.4mm Series','specDescription' => 'BL-Hxx36G 0603 0.4mm Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 4,'specTitle' => 'BL-Hxx36A 0603 0.6mm Series','specDescription' => 'BL-Hxx36A 0603 0.6mm Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 4,'specTitle' => 'BL-Hxx36D 0603 0.8mm Series','specDescription' => 'BL-Hxx36D 0603 0.8mm Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 5,'specTitle' => 'BL-Hxx35A 0805 Series','specDescription' => 'BL-Hxx35A 0805 Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 6,'specTitle' => 'BL-Hxx33 1206 Series','specDescription' => 'BL-Hxx33 1206 Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 6,'specTitle' => 'BL-Hxx33A 1206 with Inner Lens Series','specDescription' => 'BL-Hxx33A 1206 with Inner Lens Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 6,'specTitle' => 'BR-Hxx33-xx 1206 Resistor Series','specDescription' => 'BR-Hxx33-xx 1206 Resistor Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 6,'specTitle' => 'BB-Hxx33-C 1206 Blinking Series','specDescription' => 'BB-Hxx33-C 1206 Blinking Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 7,'specTitle' => 'BL-Hxx34A 1204 2.0mm Right Angle Lens Series','specDescription' => 'BL-Hxx34A 1204 2.0mm Right Angle Lens Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 7,'specTitle' => 'BL-Hxx34C 1204 1.7mm Right Angle Lens Series','specDescription' => 'BL-Hxx34C 1204 1.7mm Right Angle Lens Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 7,'specTitle' => '﻿BL-Hxx34E 0802 1.0mm Right Angle Lens Series','specDescription' => '﻿BL-Hxx34E 0802 1.0mm Right Angle Lens Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 8,'specTitle' => 'BL-Hxxxx36H 0605 Bi-Color Series','specDescription' => 'BL-Hxxxx36H 0605 Bi-Color Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 8,'specTitle' => 'BL-Hxxxx34B 1204 Right Angle Bi-Color Series','specDescription' => 'BL-Hxxxx34B 1204 Right Angle Bi-Color Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 8,'specTitle' => 'BL-Hxxxx33 1206 Bi-Color Series','specDescription' => 'BL-Hxxxx33 1206 Bi-Color Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 8,'specTitle' => 'BL-Hxxxx33B 1210 Bi-Color Series','specDescription' => 'BL-Hxxxx33B 1210 Bi-Color Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 9,'specTitle' => 'BL-Hxxxxxx36T 0605  0.4mm Tri Color Series','specDescription' => 'BL-Hxxxxxx36T 0605  0.4mm Tri Color Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 9,'specTitle' => 'BL-Hxxxxxx33F 1210 1.1mm Dual-Tri Color Series','specDescription' => 'BL-Hxxxxxx33F 1210 1.1mm Dual-Tri Color Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 9,'specTitle' => 'BL-Hxxxxxx33T 1210 1.1mm Tri Color Series','specDescription' => 'BL-Hxxxxxx33T 1210 1.1mm Tri Color Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 9,'specTitle' => 'BL-Hxxxxxx34S 1004 1.35mm Tri Color Series','specDescription' => 'BL-Hxxxxxx34S 1004 1.35mm Tri Color Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 10,'specTitle' => 'BIR-Hxx36A 0603 Infrared Emitting Diodes Series','specDescription' => 'BIR-Hxx36A 0603 Infrared Emitting Diodes Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 10,'specTitle' => 'BIR-Hxx35A 0805 Infrared Emitting Diodes Series','specDescription' => 'BIR-Hxx35A 0805 Infrared Emitting Diodes Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 10,'specTitle' => 'BIR-Hxx33 1206 Infrared Emitting Diodes Series','specDescription' => 'BIR-Hxx33 1206 Infrared Emitting Diodes Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 10,'specTitle' => 'BIR-Hxx33A 1206 With Inner Lens Infrared Emitting Diodes Series','specDescription' => 'BIR-Hxx33A 1206 With Inner Lens Infrared Emitting Diodes Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 10,'specTitle' => 'BPT-HPx36A 0603 Photo Transistors Series','specDescription' => 'BPT-HPx36A 0603 Photo Transistors Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 10,'specTitle' => 'BPT-HPx35A 0805 Photo Transistors Series','specDescription' => 'BPT-HPx35A 0805 Photo Transistors Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 10,'specTitle' => 'BPT-HPx33 1206 Photo Transistors Series','specDescription' => 'BPT-HPx33 1206 Photo Transistors Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 10,'specTitle' => 'BPD-HQx33 1206 Photo Diodes Series','specDescription' => 'BPD-HQx33 1206 Photo Diodes Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 11,'specTitle' => 'BL-Xxxx61 Axial Series','specDescription' => 'BL-Xxxx61 Axial Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 11,'specTitle' => 'BL-Xxxx61-F7 Axial Series with "Gull Wing"','specDescription' => 'BL-Xxxx61-F7 Axial Series with "Gull Wing"','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 11,'specTitle' => 'BL-Xxxx61-F8 Axial Series with  "Yoke"','specDescription' => 'BL-Xxxx61-F8 Axial Series with  "Yoke"','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 11,'specTitle' => 'BL-Xxxx61-F9 Axial Series with  "Z" Bent','specDescription' => 'BL-Xxxx61-F9 Axial Series with  "Z" Bent','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 12,'specTitle' => 'Part No. System for Chip LED Series','specDescription' => 'Part No. System for Chip LED Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 12,'specTitle' => 'Taping Chip LED','specDescription' => 'Taping Chip LED','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 12,'specTitle' => 'Soldering & Storage General Information','specDescription' => 'Soldering & Storage General Information','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 12,'specTitle' => 'Part No. System for Infrared Series','specDescription' => 'Part No. System for Infrared Series','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 1,'specTitle' => 'Ultra LED Lamps','specDescription' => 'Ultra LED Lamps','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 1,'specTitle' => 'Standard LED (Resistor LED Lamps)','specDescription' => 'Standard LED (Resistor LED Lamps)','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 1,'specTitle' => 'Standard LED (Round Types for 3Φ, 3.4Φ, 4Φ, 4.7Φ, 4.8Φ, 5Φ )','specDescription' => 'Standard LED (Round Types for 3Φ, 3.4Φ, 4Φ, 4.7Φ, 4.8Φ, 5Φ )','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 1,'specTitle' => 'Standard LED (Rectangular Types)','specDescription' => 'Standard LED (Rectangular Types)','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 1,'specTitle' => 'Standard LED (Cylindrical & Tower Types)','specDescription' => 'Standard LED (Cylindrical & Tower Types)','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 1,'specTitle' => 'Bigger size LED Lamps','specDescription' => 'Bigger size LED Lamps','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 1,'specTitle' => 'Low-Current LED Lamps','specDescription' => 'Low-Current LED Lamps','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 1,'specTitle' => 'Dual-chip LED Lamps','specDescription' => 'Dual-chip LED Lamps','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 1,'specTitle' => 'Dual-chip & Tri-State LED Lamps','specDescription' => 'Dual-chip & Tri-State LED Lamps','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 1,'specTitle' => 'Flux LED Lamps','specDescription' => 'Flux LED Lamps','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 2,'specTitle' => 'Lamp Part No System','specDescription' => 'Lamp Part No System','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 2,'specTitle' => 'Taping LED Lamp','specDescription' => 'Taping LED Lamp','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 13,'specTitle' => 'Single-Digit LED Displays','specDescription' => 'Single-Digit LED Displays','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 13,'specTitle' => 'Dual-Digit LED Displays','specDescription' => 'Dual-Digit LED Displays','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 13,'specTitle' => 'Three-Digit LED Displays','specDescription' => 'Three-Digit LED Displays','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 13,'specTitle' => 'Four-Digit LED Displays','specDescription' => 'Four-Digit LED Displays','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 14,'specTitle' => 'Bar Graph Arrays','specDescription' => 'Bar Graph Arrays','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 14,'specTitle' => 'LED Light Bar','specDescription' => 'LED Light Bar','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 15,'specTitle' => 'Single-color 5x7 Dot Matrix Displays','specDescription' => 'Single-color 5x7 Dot Matrix Displays','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 15,'specTitle' => 'Single-color 5x8 Dot Matrix Displays','specDescription' => 'Single-color 5x8 Dot Matrix Displays','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 15,'specTitle' => 'Single-color 8x8 Dot Matrix Displays','specDescription' => 'Single-color 8x8 Dot Matrix Displays','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 16,'specTitle' => 'Dot Matrix Display Part No System','specDescription' => 'Dot Matrix Display Part No System','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 16,'specTitle' => 'Display and Bar Graph & Array Part No System','specDescription' => 'Display and Bar Graph & Array Part No System','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 17,'specTitle' => 'Infrared Emitting Diode - End & Side Look','specDescription' => 'Infrared Emitting Diode - End & Side Look','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 17,'specTitle' => 'Phototransistors - End & Side Look','specDescription' => 'Phototransistors - End & Side Look','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 17,'specTitle' => 'Photodiode - End & Side Look','specDescription' => 'Photodiode - End & Side Look','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 18,'specTitle' => 'Photo Interrupters - Reflective Type','specDescription' => 'Photo Interrupters - Reflective Type','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 19,'specTitle' => 'Receiver Module','specDescription' => 'Receiver Module','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 20,'specTitle' => 'Photo Coupler','specDescription' => 'Photo Coupler','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 21,'specTitle' => 'How to use invisible products','specDescription' => 'How to use invisible products','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 21,'specTitle' => 'Infrared Series Part No System.','specDescription' => 'Infrared Series Part No System.','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 21,'specTitle' => 'Receiver Module Part No System','specDescription' => 'Receiver Module Part No System','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 21,'specTitle' => 'Photo Coupler Part No System','specDescription' => 'Photo Coupler Part No System','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 22,'specTitle' => '1 pcs LED with Holder','specDescription' => '1 pcs LED with Holder','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 22,'specTitle' => '2 pcs LED with Holder','specDescription' => '2 pcs LED with Holder','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 22,'specTitle' => '3 pcs LED with Holder','specDescription' => '3 pcs LED with Holder','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 22,'specTitle' => '4-5 pcs LED with Holder','specDescription' => '4-5 pcs LED with Holder','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 22,'specTitle' => '8 -16 pcs LED with Holder','specDescription' => '8 -16 pcs LED with Holder','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 23,'specTitle' => 'Usage and Handling Instructions','specDescription' => 'Usage and Handling Instructions','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 28,'specTitle' => 'High-Power-LED-1W&3W','specDescription' => 'High-Power-LED-1W&3W','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 29,'specTitle' => 'High-Power-LED-reflector','specDescription' => 'High-Power-LED-reflector','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 24,'specTitle' => 'MMT','specDescription' => 'Metallized Polyester Film','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 24,'specTitle' => 'EM7','specDescription' => 'METALLIZEDPOLYPROPYLENEFILM','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 24,'specTitle' => 'MEF','specDescription' => 'Metallized Polypropylene Film','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 24,'specTitle' => 'DME','specDescription' => 'Metallized Polyester Film','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 24,'specTitle' => 'MEM','specDescription' => 'Metallized Polyester Film','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 24,'specTitle' => 'MEA','specDescription' => 'Metallized Polyester Film','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 24,'specTitle' => 'MET','specDescription' => 'Metallized Polyester Film','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 24,'specTitle' => 'MEY','specDescription' => 'Metallized Polyester Film','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 25,'specTitle' => 'MPP','specDescription' => 'Metallized Polypropylene Film','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 25,'specTitle' => 'MPM','specDescription' => 'Metallized Polypropylene Film','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 25,'specTitle' => 'MPT','specDescription' => 'Metallized Polypropylene Film','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 25,'specTitle' => 'MPA','specDescription' => 'Metallized Polypropylene Film','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 25,'specTitle' => 'MPX-1','specDescription' => 'Metallized Polypropylene Film','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 25,'specTitle' => 'MPX-2','specDescription' => 'Metallized Polypropylene Film','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 26,'specTitle' => 'PEI','specDescription' => 'Polyester Film','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 26,'specTitle' => 'PEN','specDescription' => 'Polyester Film','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 27,'specTitle' => 'PPN','specDescription' => 'Polypropylene Film','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 27,'specTitle' => 'PPS','specDescription' => 'Polypropylene Film','specPdfUrl' => null, 'specPdfName' => null],
            ['itemsGroupId' => 27,'specTitle' => 'PPT','specDescription' => 'Polypropylene Film','specPdfUrl' => null, 'specPdfName' => null],
        ]);
    }
}
